"""initial migration

Revision ID: 698b97c6ae9d
Revises: 
Create Date: 2024-09-12 00:30:20.271024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698b97c6ae9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('alumnos_tutores_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendance', 'alumnos_tutores', ['alumnos_tutores_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'alumnos_tutores_id')
    # ### end Alembic commands ###
